# Generated by Django 5.2.13 on 2026-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
